[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
verbosity = 3
remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config